### ISSUE TITLE
Missing quoting of special characters in EPUB documentation

### ISSUE THREAD

**Issue by pkoning2** [tabemann/zeptoforth#77]
Epub is a variant of xhtml, which means that `<` and `>` are special characters.  But a number of the source files for the documentation have strings in them like `<object>` (in oo.xhtml).  That's not valid because that would be an XHTML tag, and `<object>` is not a defined tag.  So when viewing the resulting epub file, I end up either with those strings missing , or with the chapter truncated at that point.
The solution is to HTML-quote those characters, as in `&lt;object&gt;`.
I guess that the actual sources for the docs are .md files, so I'm puzzled that the machinery for processing those into xhtml and then into epub partly gets this right and partly not.  For example, in the "oo" chapter, just after the example I see "Here we define two classes, &lt;my-class&gt; and ..." and those are quoted properly.  But a few paragraphs later I see: "To practically use this object system, one has to consider how to create s." which should be "To practically use this object system, one has to consider how to create &lt;object&gt;s."  No quoting there.

**Comment by tabemann** [comment]
I have made the documentation fixes, which are now in the `master` and `devel` branches. It turned out that things in angle brackets in backquotes (to mark it as code) are not treated as XHTML tags, but things in angle brackets not in quotation which are not preceded by a backslash are treated as XHTML tags. These changes will be in the next release, but a new release probably not be coming immediately unless I run into a bug which needs fixing (as currently the only thing pending is my SNTP client, and while I have an ST7735S driver in the works, I won't be able to test it until I get my Waveshare board from China anyways).

**Comment by pkoning2** [comment]
Looks good.
